### ISSUE TITLE
Ошибка при указании параметра --dir или -d на OS X

### ISSUE THREAD

**Issue by phoenix-lib** [alekseylovchikov/ch-download#17]
Если указывать параметр --dir или -d на Mac, получаем ошибку "Check your email or password". Но это не настоящая ошибка.

Код настоящей ошибки.
```
{ Error: EISDIR: illegal operation on a directory, mkdir '/'
    at Object.mkdirSync (fs.js:752:3)
    at downloadFolder.split.reduce (/Users/phoenix/projects/phoenix-group.by/node_modules/parsecoursehunters/src/create/createFolder.js:12:10)
    at Array.reduce (<anonymous>:null:null)
    at createFolder (/Users/phoenix/projects/phoenix-group.by/node_modules/parsecoursehunters/src/create/createFolder.js:9:29)
    at runGetVideos (/Users/phoenix/projects/phoenix-group.by/node_modules/parsecoursehunters/index.js:81:3)
    at getToken.then.token (/Users/phoenix/projects/phoenix-group.by/node_modules/parsecoursehunters/index.js:66:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 errno: -21, syscall: 'mkdir', code: 'EISDIR', path: '/' }
```

В функции createFolder(downloadFolder) когда происходит проверка на наличие директории / на Mac функция fs.mkdirSync(curDir) возвращает код ошибки EISDIR который сейчас никак не обрабатывается и падает с ошибкой "Check your email or password".

Рабочая функция: 

```
function createFolder(downloadFolder) {
  const sep = path.sep;
  const initDir = path.isAbsolute(downloadFolder) ? sep : '';
  downloadFolder.split(sep).reduce((parentDir, childDir) => {
    const curDir = path.resolve(parentDir, childDir);
    try {
      fs.mkdirSync(curDir);
    } catch (err) {
      if (err.code !== 'EEXIST' && err.code !== 'EISDIR') {
        throw err;
      }
      if (curDir == makeDownloadFolderPath(downloadFolder))
        console.log(`Directory ${curDir} already exists`.blue);
      return curDir;
    }
    console.log(`Directory ${curDir} created`.blue);
    return curDir;
  }, initDir);
}
```

Если требуется могу отправить Pull Request с исправлением.

**Comment by alekseylovchikov** [comment]
Привет! Да, давай в pull request

**Comment by alekseylovchikov** [comment]
fixed
