### ISSUE TITLE
I am getting error while downloading specific video

### ISSUE THREAD

**Issue by pintu1991** [alekseylovchikov/ch-download#24]
coursehunters -u https://coursehunters.net/course/frontendmaster-deep-foundations-of-advanced-js -d /var/www/html/Deep-JavaScript-Basics/

error -
Starting app...

File /var/www/html/Deep-JavaScript-Basics//videos.txt created
/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/src/download/getVideos.js:36
              const videoName = `${index + 1} ` + el.children[0].data.replace(/[\/:*?"<>|]/g, '');
                                                                 ^

TypeError: Cannot read property 'data' of undefined
    at filterSpan.map.el (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/src/download/getVideos.js:36:66)
    at Array.map (<anonymous>:null:null)
    at Node.<anonymous> (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/src/download/getVideos.js:33:22)
    at testFn (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/cheerio/lib/api/traversing.js:320:22)
    at /home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/lodash/_baseFilter.js:14:9
    at /home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/lodash/_createBaseEach.js:24:11
    at baseFilter (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/lodash/_baseFilter.js:13:3)
    at filter (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/lodash/filter.js:45:10)
    at initialize.filter (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/cheerio/lib/api/traversing.js:330:28)
    at Request._callback (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/src/download/getVideos.js:23:28)
    at Request.self.callback (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/home/prashant/.nvm/versions/node/v10.14.1/lib/node_modules/parsecoursehunters/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
    at IncomingMessage.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)

**Comment by pintu1991** [comment]
I found the cause of the issue -
Course I am downloading videos that does not have name so on this line - const videoName = ${index + 1} + el.children[0].data.replace(/[/:*?"<>|]/g, '');

"el.children[0].data.replace(/[/:*?"<>|]/g, '');"  - this code is trying to get name, so it gives error undefind

Replace this line (line no 36) -  
              const videoName = `${index + 1} ` + el.children[0].data.replace(/[\/:*?"<>|]/g, '');
to this -
              const videoName = 'Lesson ' + `${index + 1} `;
Will solve the issue for temporary for the course videos which does not have name.

**Comment by baixiaoji** [comment]
having the same error
