### ISSUE TITLE
Not able to download get this error?

### ISSUE THREAD

**Issue by sankalpgaikwad** [alekseylovchikov/ch-download#50]
node index.js -u https://coursehunter.net/course/100-dney-koda-polnyy-uchebnyy-kurs-python-pro  -e ******* -p ********** 

https://coursehunter.net/course/prodvinutye-patterny-bezopasnosti-react
C:\Users\ch-download-master\src\download\getVideos.js:27
  return materialsAnchorEl.get()[0]?.attribs.href;
                                    ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:1053:16)
    at Module._compile (internal/modules/cjs/loader.js:1101:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\ch-download-master\ch-download-master\index.js:23:19)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)

**Comment by ligowsky** [comment]
@sankalpgaikwad what version of node do you use? Try install 14.16.1 LTS, it fixes `SyntaxError: Unexpected token '.'`
But then you will receive an another error `TypeError: Cannot read property 'slice' of null`

The fix isn't obvious, but pretty simple: 
1. Clone a [fork](https://github.com/jivan99/ch-download) of this repository:
`git clone https://github.com/jivan99/ch-download`
2. Navigate to the downloaded folder
`cd ch-download`
3. Switch to the branch "fix-download-error"
`git checkout fix-download-error`
4. Install node modules (make sure you're using Node 14.16.1)
`npm install`
5. Run the downloader
`node index.js -u course-url -e email -p password [-d dirname] [-l lessons]`
